namespace JunkEmailCleaner;

internal static class BlockedSenderNames
{
    // Matches are case-insensitive substrings of the sender display name shown by Outlook.
    internal static readonly string[] Values =
    [
        "AARP ",
        "American Home Shield",
        "Americor Associate",
        "Bad Credit",
        "BarkBox",
        "BetterHelp",
        "Blissy",
        "Brinks Home",
        "BrinksHomeOffer",
        "CarShield",
        "ClearChoice",
        "ColonialPenn",
        "Cornerstone Law Ad",
        "CreditCard",
        "Debt Relief",
        "Destiny | Credit Card",
        "Destiny Mastercard",
        "EasyCanvasPrints",
        "EasyCanvasPrints",
        "eHarmony",
        "Endurance",
        "Ethos Coverage",
        "Ethos Life",
        "Fresh_Reviews",
        "Goldco Direct",
        "HealthCare.com",
        "HexClad",
        "House Project Pros",
        "JacuzziBathRemodelPromo",
        "Jenny Craig",
        "Keranique",
        "LaserAway Studio",
        "LawsuitFinder",
        "LendingForAllCredit",
        "Liberty Mutual",
        "Life Line Screening",
        "LifeLineScreening",
        "Liz Buys Houses",
        "Liz.Buys.Houses",
        "Liz-Buys-Houses",
        "Liz_Buys_Houses",
        "Liz Buys_Houses",
        "loanDepot",
        "Metal Roofing Innovations",
        "Milestone Cashback",
        "NationalDebtRelief",
        "NorthStar-Loans",
        "Norton",
        "NDR Affiliate",
        "Optima - Tax",
        "Optima_Tax_Relief",
        "Orangetheory",
        "RenewalbyAndersen",
        "Renewal by Andersen Replacement Windows",
        "Roof Replacement",
        "Saatva",
        "She'll BEG for your meat",
        "SBLI.com",
        "ShopMiracleBrand",
        "Tennis Channel",
        "the Milestone Card",
        "The Destiny",
        "The PhotoStick",
        "TheCapitalWallet",
        "TRA.com",
        "TRA Services",
        "TruthFinder",
        "Unclaimed",
        "Vehicle Protection",
        "Visible Partner Deal",
        "Vivint",
        "WarbyParker.com",
        "Warranty",
        "Wild Seafood",
        "Your meat",
        "YouthAddictionLawsuits.com",
     ];
}
