namespace JunkEmailCleaner;

internal static class BlockedSenderNames
{
    // Matches are case-insensitive substrings of the sender display name shown by Outlook.
    internal static readonly string[] Values =
    [
        "AARP Invitation for You",
        "AARP Join Opportunity",
        "American Home Shield",
        "Americor Associate",
        "BarkBox",
        "BetterHelp",
        "Blissy",
        "Brinks Home",
        "BrinksHomeOffer",
        "CarShield",
        "ClearChoice Dental",
        "ColonialPenn",
        "Cornerstone Law Ad",
        "Debt Relief",
        "Destiny | Credit Card",
        "EasyCanvasPrints",
        "EasyCanvasPrints",
        "eHarmony",
        "Endurance Auto",
        "Ethos Coverage",
        "Ethos Life",
        "Fresh_Reviews",
        "Goldco Direct",
        "HealthCare.com",
        "HexClad",
        "House Project Pros",
        "JacuzziBathRemodelPromo",
        "Jenny Craig",
        "Keranique",
        "LaserAway Studio",
        "LendingForAllCredit",
        "Liberty Mutual",
        "Life Line Screening",
        "LifeLineScreening",
        "Liz Buys Houses",
        "Liz.Buys.Houses",
        "Liz-Buys-Houses",
        "Metal Roofing Innovations",
        "Milestone Cashback",
        "NationalDebtRelief",
        "NorthStar-Loans.com",
        "Optima - Tax",
        "Optima_Tax_Relief",
        "Orangetheory",
        "Renewal by Andersen Replacement Windows",
        "Saatva",
        "SBLI.com",
        "ShopMiracleBrand",
        "Tennis Channel",
        "the Milestone Card",
        "The PhotoStick",
        "TheCapitalWallet",
        "TRA.com",
        "Vivint Smart Home",
        "WarbyParker.com",
        "YouthAddictionLawsuits.com",
     ];
}
